### ISSUE TITLE
Add example of watching a node that represent an array of Dinosors

### ISSUE THREAD

**Issue by fallais** [ereyes01/firebase#9]
Hello,

I'm a bit confused with the understanding of the parser function and the Resource.(*Dinosor) at the end of the event for. Would it be possible to add an example of watching a node that represent an array of Dinosors please ?

If I well understand, we need to create a function that is in charge of "updating" le the node we receive at the begining of the watch, otherwise, the data become false.

Thanks a lot.

**Comment by ereyes01** [comment]
Not 100% sure I understand your question, but I will try to explain the parser function...

- Listen to a Firebase location. The updates will arrive as raw JSON strings.
- Most likely, the raw JSON represents a Go struct you've defined somewhere... let's call it `Foo`
- You provide a parser function that unmarshals the JSON into a `Foo` instance.
- An update arrives, now we have the raw JSON.
- The raw JSON is sent to your parser function.
- The channel sends you that object as an `interface{}`... you type-assert to a `Foo` type.

If you need to review how type assertions work, I suggest you review this part of the Go Language Tour: https://tour.golang.org/methods/15

Issue #2 proposes a better way of doing this that I think will make this library much easier to use. However, I've moved on to other things in my work lately, and haven't had the time to get back to this yet. Have a look at #2 and let me know what you think.

Thanks, Eddy

**Comment by fallais** [comment]
@ereyes01 : Thanks a lot for the explanation, that is what I understood. At the first call, everything is good, as the big node received can be unmarshalled in my map of struct. But after, I only receive an update containing only the change and the path, so.. things are not so simple. I mean I cannot only type-assert it.

Right ?

**Comment by ereyes01** [comment]
Yes, actually, you are correct. If the updates you get are partial (i.e. just one element of a multi-key object), you will not be able to blindly unmarshal and type assert.

In that case, you have a few options:

- Provide a `nil` unmarshaller callback, and you will get `map[string]interface{}`
- Provide an unmarshaller that inspects the changed path (one of the parameters in the function signature) and acts accordingly

For instance, if your DB looks like:

```json
"top": {
    "record1": {
        "a": 10,
        "b": 20
    }
}
```

and then you set top.record1.a = 20, you will get a raw event that looks like (assuming your are watching top.json/):

`{"path": "/record1/a", "data": 20}`

Whereas if you to add "{"record2": {"a":100, "b": 200}}", that would give you:

`{"path": "/record2", "data": {"a":100, "b": 200}}`

... and in this case, you could unmarshal updates if path is 1 level deep (assuming a stable data model) into a struct:

```go
type Foo struct {
    A int
    B int
}
```

My applications typically only watch for new objects instead of changes to existing ones, so unmarshalling to a type makes sense for my usage (only full objects show up in my change streams). Otherwise, you'd have to either write a more sophisticated unmarshaller that keys off of the changed path, or just settle for `map[string]insterface{}`.

Hope that makes sense?

**Comment by fallais** [comment]
Hello, thanks for your time ! Yes we are in phase ;)
I need to unmarshal based on the path.

Things is.. at this point, is there, and I'm sure yes, a way to do it generically, one time, and for all kind of watches.. I mean a global parser. Key point for the relatime sync for Firebase.

**Comment by ereyes01** [comment]
A global parser for everything would be really nice. I think the model behind Firebase's streaming REST design is that the user maintains a cache of everything he is watching, and based on the updates, keep the cache current.

In order to create a true global parser, I think you would have to follow that model and implement a cache of your objects (starting with the first update). That way, you can apply the partial update to your cache as each change arrives.

Without the cache, you would have to do multiple queries (i.e. GET the rest of the object)... but then your multiple operations would not be atomic with each other.

Disclaimer: I don't work for Firebase :-)
